[package]
name = "ria-faster"
version = "0.1.0"
authors = ["Aaron Lee <alee@aaronosaur.us>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
